Bigint_done
timonchiks/HSE-Course pull request #2
Opened 2020-11-29 12:04 UTC by timonchiks

for_Igor

2020-12-07 21:28 UTC, lgAshanl requested changes

2020-12-07 21:28 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.cpp
> +}
Копированиф. Лишние копирования

2020-12-08 10:22 UTC, timonchiks commented on module-1/homework/BigInteger/biginteger.cpp
> +}
Исправил

2020-12-09 20:37 UTC, lgAshanl requested changes

2020-12-09 20:37 UTC, lgAshanl commented on module-1/homework/BigInteger/biginteger.h
> +        int zn = 1;
Класс-Саша Грей. Добавь приватности

2020-12-16 10:03 UTC, merged